name: Fetch Static Fragrance Data

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fetch-static-fragrance-data-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Sync dependencies (locked)
        run: uv sync --frozen

      - name: Run processor
        run: uv run collect_missing_data.py

      - name: Show changes
        run: |
          git status --porcelain
          git diff --stat || true
